// Generated by gencpp from file my_turtlebot_navigation/NavMessage.msg
// DO NOT EDIT!


#ifndef MY_TURTLEBOT_NAVIGATION_MESSAGE_NAVMESSAGE_H
#define MY_TURTLEBOT_NAVIGATION_MESSAGE_NAVMESSAGE_H

#include <ros/service_traits.h>


#include <my_turtlebot_navigation/NavMessageRequest.h>
#include <my_turtlebot_navigation/NavMessageResponse.h>


namespace my_turtlebot_navigation
{

struct NavMessage
{

typedef NavMessageRequest Request;
typedef NavMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavMessage
} // namespace my_turtlebot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_turtlebot_navigation::NavMessage > {
  static const char* value()
  {
    return "920ca5ca095e1b5230fc32da338a974c";
  }

  static const char* value(const ::my_turtlebot_navigation::NavMessage&) { return value(); }
};

template<>
struct DataType< ::my_turtlebot_navigation::NavMessage > {
  static const char* value()
  {
    return "my_turtlebot_navigation/NavMessage";
  }

  static const char* value(const ::my_turtlebot_navigation::NavMessage&) { return value(); }
};


// service_traits::MD5Sum< ::my_turtlebot_navigation::NavMessageRequest> should match
// service_traits::MD5Sum< ::my_turtlebot_navigation::NavMessage >
template<>
struct MD5Sum< ::my_turtlebot_navigation::NavMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_turtlebot_navigation::NavMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::NavMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_turtlebot_navigation::NavMessageRequest> should match
// service_traits::DataType< ::my_turtlebot_navigation::NavMessage >
template<>
struct DataType< ::my_turtlebot_navigation::NavMessageRequest>
{
  static const char* value()
  {
    return DataType< ::my_turtlebot_navigation::NavMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::NavMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_turtlebot_navigation::NavMessageResponse> should match
// service_traits::MD5Sum< ::my_turtlebot_navigation::NavMessage >
template<>
struct MD5Sum< ::my_turtlebot_navigation::NavMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_turtlebot_navigation::NavMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::NavMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_turtlebot_navigation::NavMessageResponse> should match
// service_traits::DataType< ::my_turtlebot_navigation::NavMessage >
template<>
struct DataType< ::my_turtlebot_navigation::NavMessageResponse>
{
  static const char* value()
  {
    return DataType< ::my_turtlebot_navigation::NavMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::NavMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_TURTLEBOT_NAVIGATION_MESSAGE_NAVMESSAGE_H
