obstacle_range: 1.0
raytrace_range: 1.5

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]

cost_scaling_factor: 5.0 # scaling factor to apply to cost values during inflation
map_type: costmap


# robot_radius: 0.06
# footprint_padding: 0.1
# robot_base_frame: base_footprint
# obstacle_range: 1.0
# raytrace_range: 1.5

# footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
# resolution: 0.05


# cost_scaling_factor: 5.0
# map_type: costmap
# transform_tolerance: 0.5


# #layer definitions
# static:
#     map_topic: /map
#     subscribe_to_updates: true

# obstacles_layer:
#     observation_sources: laser
#     laser: {sensor_frame: base_scan, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, obstacle_range: 5.5}

# inflation:
#     inflation_radius: 0.4