NavfnROS:
  visualize_potential: true    
  allow_unknown: true  # allow navfn to create plans that traverse unknown space       
                                
  planner_window_x: 0.0         
  planner_window_y: 0.0         

  default_tolerance: 0.05